version: '3.8'

volumes:
  vendor:
  var:

services:
  php:
    container_name: boozt_php
    build:
      context: ./
      dockerfile: build/docker/Dockerfile
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www/html

  nginx:
    container_name: boozt_nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www/html
      - ./build/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
